
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomCursor from "../components/CustomCursor";
import ClientLayoutProvider from "../components/ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
const oakesGroteskFontFace = `
  @font-face {
    font-family: 'Oakes Grotesk';
    src: url('${basePath}/fonts/OakesGrotesk-SemiBold.woff2') format('woff2'),
         url('${basePath}/fonts/OakesGrotesk-SemiBold.woff') format('woff');
    font-weight: 600;
    font-style: normal;
    font-display: swap;
  }

  html, body {
    font-family: 'Oakes Grotesk', Arial, sans-serif;
  }
`;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <style>{oakesGroteskFontFace}</style>
      </head>
      <body className="min-h-full flex flex-col bg-zinc-50 dark:bg-black">
        <CustomCursor />
        <ClientLayoutProvider>{children}</ClientLayoutProvider>
      </body>
    </html>
  );
}
